### ISSUE TITLE
Name input did not have limit

### ISSUE THREAD

**Issue by sri-inovator** [fssa-batch3/meganathan.subramanian__web_project#11]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiN2U3ZjI3YjItY2ExYS00YjI3LTkzZjQtMmFiMzNiMDM5ZDYyIiwiZGVwbG95X2lkIjoiNjQzOTVkNTJmMDI3NDMwMDA4ZDlkMDU3IiwiaWQiOiI1YzQ3NjA1MS1hY2RjLTQwZjEtOTE4Zi1mMTg1ZDRlYjcyYTkifQ==)

### Description of issue
Name input did not have limit

### Expected result
Name section have limit 

### Actual result
Name section have limitless

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/account/edit-profile
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-6--bookztore.netlify.app%2Fpages%2Faccount%2Fedit-profile&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #6](https://deploy-preview-6--bookztore.netlify.app/pages/account/edit-profile)

**Comment by meganathan2003** [comment]
Fixed the issue

**Comment by sri-inovator** [comment]
Tested sucessfully
