### ISSUE TITLE
Inputs not have limit and required 

### ISSUE THREAD

**Issue by sri-inovator** [fssa-batch3/meganathan.subramanian__web_project#15]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiN2U3ZjI3YjItY2ExYS00YjI3LTkzZjQtMmFiMzNiMDM5ZDYyIiwiZGVwbG95X2lkIjoiNjQ1ZmQzODMyYWZjMzQwMDA4NzVkZjAzIiwiaWQiOiI2MjM4MDc2Ny0zN2Y1LTRmZjMtOTI1Yy03YWJiNGNiZDQyZTEifQ==)

### Description of issue
phone number input accept more than 10 numbers ,city and state input accept numbers

### Expected result
number input must have limit and city, state input did not accept numbers

### Actual result
phone number input accept more than 10 numbers ,city and state input accept numbers

### Steps to reproduce
1. After login, go to profile page
2. edit phone number and city, state inputs
3. give more than 10 numbers in phone input and give numbers in city, state input

```
Path:      /pages/account/edit-profile
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-6--bookztore.netlify.app%2Fpages%2Faccount%2Fedit-profile&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #6](https://deploy-preview-6--bookztore.netlify.app/pages/account/edit-profile)

**Comment by meganathan2003** [comment]
This issued is Solved

**Comment by sri-inovator** [comment]
Tested sucessfully
